### PR TITLE
First pass at building with Meson

### PR DESCRIPTION
**Pull request by llasram**
Still same caveats per https://github.com/jdykstra/ucsd-psystem-vm/pull/9.

### CODE REVIEW

**Comment by jdykstra** [comment]
Basically same question as for FS—is this ready to be committed?  If not, please hold off on the pull request until you think it’s ready.  Thanks!

**Comment by llasram** [comment]
@jdykstra Yep!  Per my response over on `fs`, I do think this one is ready for review and merging if it looks good.

**Review by jdykstra — APPROVED** [review]
This is a stroke for good just on its own.

**Comment by jdykstra** [comment]
I meant getting rid of the sed script.

**Pull request merged**
